### ISSUE TITLE
Let's make it "Votes" instead of "Clicks" 

### ISSUE THREAD

**Issue by leonerichsen** [RadicalxChange/quadratic-voting#11]
@alexrandaccio

<img width="1417" alt="Bildschirmfoto 2021-05-02 um 19 21 29" src="https://user-images.githubusercontent.com/59769856/116821823-b58a5100-ab7b-11eb-9b76-2bb52f72f24b.png">

**Comment by alexrandaccio** [comment]
I removed any reference to "voting" or "votes" at the request of a client for the purposes of a specific use case. If you look at the codebase, you will see that I constrained these changes to a branch called "colorado". The master branch still uses the word "votes." My plan was to deploy the "colorado" branch for the duration of that event, then switch back to master.

The event is over now, so I'll be redeploying the master branch today. Closing this issue as it will be resolved by the redeployment.

**Comment by leonerichsen** [comment]
Oh, my fault -- thanks, Alex!
