### ISSUE TITLE
Remove "edit" date ability?

### ISSUE THREAD

**Issue by skyminert** [RadicalxChange/quadratic-voting#20]
Hi, Great tool!  

On the page:
https://quadraticvote.radicalxchange.org/event?id=93cebe53-2dd8-4291-aee4-94c45bd5cf38

I see the ability for anyone to edit the "Event Start Date" and the "Event End Date".

Screenshot:
![image](https://user-images.githubusercontent.com/57817726/163077727-5753f2a9-fa29-4fa6-8c80-50ea7bc2da63.png)

Should this is available to anyone?  Thanks

**Comment by alexrandaccio** [comment]
fixed in 73c341e320568f1a364f674fdf22f8a10b41d386. Thanks @skyminert !
